image: docker:latest
# Pick zero or more services to be used on all builds.
  script:
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

all_tests:
  image: node:7.10.0
  script:
   - npm install
   - npm test

before_script:
  - docker info

deploy:
  script:
   - docker build -t web-app .
   - docker run -p 49491:1337 -d web-app 
